"""initial schema

Revision ID: fe58c2cc0324
Revises: 
Create Date: 2026-04-19 18:30:29.259460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe58c2cc0324'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cost_inr', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_calls_agent'), 'agent_calls', ['agent'], unique=False)
    op.create_index(op.f('ix_agent_calls_created_at'), 'agent_calls', ['created_at'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_hash'), 'news_articles', ['hash'], unique=True)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('delisted_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('agent_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('asof_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reports_query_hash'), 'agent_reports', ['query_hash'], unique=False)
    op.create_index(op.f('ix_agent_reports_ticker'), 'agent_reports', ['ticker'], unique=False)
    op.create_table('article_tickers',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('article_id', 'ticker')
    )
    op.create_index('ix_article_tickers_ticker', 'article_tickers', ['ticker'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ratio_num', sa.Float(), nullable=True),
    sa.Column('ratio_den', sa.Float(), nullable=True),
    sa.Column('dividend_per_share', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'ex_date', 'kind', name='uq_corp_action')
    )
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ticker'), 'corporate_actions', ['ticker'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('conviction', sa.Integer(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('ref_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_decisions_ticker'), 'decisions', ['ticker'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filings_filed_at'), 'filings', ['filed_at'], unique=False)
    op.create_index(op.f('ix_filings_hash'), 'filings', ['hash'], unique=True)
    op.create_index(op.f('ix_filings_ticker'), 'filings', ['ticker'], unique=False)
    op.create_table('fundamentals_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'snapshot_at', name='uq_fund_snap')
    )
    op.create_index(op.f('ix_fundamentals_snapshots_snapshot_at'), 'fundamentals_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_fundamentals_snapshots_ticker'), 'fundamentals_snapshots', ['ticker'], unique=False)
    op.create_table('surveillance_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('list_name', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('added_on', sa.Date(), nullable=False),
    sa.Column('removed_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveillance_flags_added_on'), 'surveillance_flags', ['added_on'], unique=False)
    op.create_index(op.f('ix_surveillance_flags_ticker'), 'surveillance_flags', ['ticker'], unique=False)
    op.create_table('ticker_aliases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'alias', name='uq_ticker_alias')
    )
    op.create_index(op.f('ix_ticker_aliases_alias'), 'ticker_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_ticker_aliases_ticker'), 'ticker_aliases', ['ticker'], unique=False)
    op.create_table('watchlist',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('decision_outcomes',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('horizon', sa.String(length=8), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('decision_id', 'horizon')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_outcomes')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_ticker_aliases_ticker'), table_name='ticker_aliases')
    op.drop_index(op.f('ix_ticker_aliases_alias'), table_name='ticker_aliases')
    op.drop_table('ticker_aliases')
    op.drop_index(op.f('ix_surveillance_flags_ticker'), table_name='surveillance_flags')
    op.drop_index(op.f('ix_surveillance_flags_added_on'), table_name='surveillance_flags')
    op.drop_table('surveillance_flags')
    op.drop_index(op.f('ix_fundamentals_snapshots_ticker'), table_name='fundamentals_snapshots')
    op.drop_index(op.f('ix_fundamentals_snapshots_snapshot_at'), table_name='fundamentals_snapshots')
    op.drop_table('fundamentals_snapshots')
    op.drop_index(op.f('ix_filings_ticker'), table_name='filings')
    op.drop_index(op.f('ix_filings_hash'), table_name='filings')
    op.drop_index(op.f('ix_filings_filed_at'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_decisions_ticker'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_corporate_actions_ticker'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index('ix_article_tickers_ticker', table_name='article_tickers')
    op.drop_table('article_tickers')
    op.drop_index(op.f('ix_agent_reports_ticker'), table_name='agent_reports')
    op.drop_index(op.f('ix_agent_reports_query_hash'), table_name='agent_reports')
    op.drop_table('agent_reports')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_hash'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_agent_calls_created_at'), table_name='agent_calls')
    op.drop_index(op.f('ix_agent_calls_agent'), table_name='agent_calls')
    op.drop_table('agent_calls')
    # ### end Alembic commands ###
